# Generated by Django 4.2 on 2023-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de nascimento')),
                ('notificar_por_email', models.BooleanField(blank=True, default=True, verbose_name='Notificar?')),
            ],
            options={
                'verbose_name': 'Aniversariante',
                'verbose_name_plural': 'Aniversariantes',
            },
        ),
    ]
