# Generated by Django 4.2 on 2023-05-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_birthdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdays',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
