# Generated by Django 4.2 on 2023-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_birthdays_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='perfil/images'),
        ),
    ]
