# Generated by Django 4.2 on 2023-05-28 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_birthdays_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='birthdays',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/images'),
        ),
    ]
