# Generated by Django 4.2 on 2023-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_birthdays_user_alter_birthdays_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdays',
            old_name='data_nascimento',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='birthdays',
            old_name='imagem',
            new_name='image_birthdays',
        ),
        migrations.RenameField(
            model_name='birthdays',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='birthdays',
            old_name='notificar_por_email',
            new_name='notify_by_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
    ]
